[INIT] create: husky p6

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -12,7 +12,7 @@ branchName=$(git branch | grep '*' | sed 's/* //')
 
 if [ $branchName == 'master' ]
 then
-  echo -e "\n[${RED}error${RESET}] Commit directly to master branch is not allowed!\n" && exit 1
+  echo "\n[${RED}error${RESET}] Commit directly to master branch is not allowed!\n" && exit 1
 fi
 
 if [ $branchName == 'develop' ]
@@ -21,14 +21,14 @@ then
 fi
 
 if [[ $branchName != "AW-"[0-9][0-9][0-9][0-9]* ]]; then
-    echo -e "\n[${RED}error${RESET}] Branch name must start with 'AW-' followed by 4 digits." && exit 1
+    echo "\n[${RED}error${RESET}] Branch name must start with 'AW-' followed by 4 digits." && exit 1
 fi
 
 if [[ ! $branchName =~ ^AW- ]]; then
-    echo -e "\n[${RED}error${RESET}] Branch name must start with 'AW-' in uppercase letters." && exit 1
+    echo "\n[${RED}error${RESET}] Branch name must start with 'AW-' in uppercase letters." && exit 1
 fi
 
-echo -e "[${GREEN}success${RESET}] Finish checking branch name.\n"
+echo "[${GREEN}success${RESET}] Finish checking branch name.\n"
 
 npm run lint
 
