[INIT] create: husky p5

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,25 +1,20 @@
-#!/bin/bash
+  #!/bin/bash
 
-RED='\033[0;31m'
-YELLOW='\033[0;33m'
-GREEN='\033[0;32m'
-RESET='\033[0m'
+  RED='\033[0;31m'
+  YELLOW='\033[0;33m'
+  GREEN='\033[0;32m'
+  RESET='\033[0m'
 
-echo "\n[${YELLOW}checking${RESET}] Pre-push Hook: Checking branch name..."
+  echo "\n[${YELLOW}checking${RESET}] Pre-push Hook: Checking branch name..."
 
-BRANCH=`git rev-parse --abbrev-ref HEAD`
-PROTECTED_BRANCHES="master"
+  BRANCH=`git rev-parse --abbrev-ref HEAD`
+  PROTECTED_BRANCHES="master"
 
-if [[ $1 != *"$BRANCH"* ]]
-then
-  echo "\n[${RED}error${RESET}] You must use (git push origin $BRANCH).\n" && exit 1
-fi
+  if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
+  then
+    echo "\n[${RED}error${RESET}] Cannot push to remote $BRANCH branch, please create your own branch and use PR.\n" && exit 1
+  fi
 
-if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
-then
-  echo "\n[${RED}error${RESET}] Cannot push to remote $BRANCH branch, please create your own branch and use PR.\n" && exit 1
-fi
+  echo "[${GREEN}success${RESET}] Finish checking branch name.\n"
 
-echo "[${GREEN}success${RESET}] Finish checking branch name.\n"
-
-exit 0
+  exit 0
